version: "3.9"

services:
  sqlai-hub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlai-hub
    volumes:
      - ~/chroma/chroma-data:/chroma/chroma/
    ports:
      - "8501:8501"
    command: streamlit run src/Chat.py
    restart: unless-stopped
    network_mode: bridge
